### ISSUE TITLE
Type inference instead of`typedFetch`

### ISSUE THREAD

**Issue by erikash** [venables/typed-route-handler#1]
Hi,
@venables, I came across this repo and it looks super interesting!

I definitely plan to give it a try soon :)

Until then - 
Given your example:
```
type ResponseData = {
  result: string
  over: number
}

export const GET = handler<ResponseData>(async (req) => {
  return NextResponse.json({
    result: "this response is type-checked",
    over: 9000
  })
})
```

It seems possible to use type inference to create a type-safe helper safer than `typedFetch`

Something like this: (according to GPT4)
```
import { GET } from './your-nextjs-router-file'; // Update the path accordingly

type ResponseData = ReturnType<typeof GET>;

async function fetchData(): Promise<ResponseData> {
  const response = await fetch('/your-api-endpoint'); // Update the API endpoint
  const responseData: ResponseData = await response.json();
  return responseData;
}

fetchData().then(data => {
  console.log(data); // This will have the correct type ResponseData
}).catch(error => {
  console.error('Error fetching data:', error);
});
```

Of course you would need to generalize it accept any `GET` and return the correct type

WDYT?

Erik.

**Comment by venables** [comment]
Thanks! Really appreciate this idea.  The challenge there would be that your API code could get included in the client bundle if you're not careful, which can be dangerous.  

Either way,  I've recently significantly reduced the scope of this package to leave the client-specific stuff to developers on their own, so this is no longer an issue.

Thanks again for the feedback!
